<a href="https://colab.research.google.com/github/shreyas27092004/Data-Handling/blob/main/20221CSD0117_27-03-2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
df=pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [30]:
df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.00,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.45,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.00,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.75,Q

In [25]:
age_mean_value=df['Age'].mean()
df['Age']=df['Age'].fillna(age_mean_value)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [26]:
df.drop("Cabin",axis=1,inplace=True)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [27]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [28]:
df.tail(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.00,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.45,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.00,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.75,Q

In [31]:
filtered_age=df[df.Age>40]
filtered_age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,S
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,S
...,...,...,...,...,...,...,...,...,...,...,...
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C

In [34]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [32]:
sorted_passengers=df.sort_values('Name',ascending=True,kind='heapsort')

In [33]:
sorted_passengers.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
845,846,0,3,"Abbing, Mr. Anthony",male,42.0,0,0,C.A. 5547,7.5500,S
746,747,0,3,"Abbott, Mr. Rossmore Edward",male,16.0,1,1,C.A. 2673,20.2500,S
279,280,1,3,"Abbott, Mrs. Stanton (Rosa Hunt)",female,35.0,1,1,C.A. 2673,20.2500,S
308,309,0,2,"Abelson, Mr. Samuel",male,30.0,1,0,P/PP 3381,24.0000,C
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,C
365,366,0,3,"Adahl, Mr. Mauritz Nils Martin",male,30.0,0,0,C 7076,7.2500,S
401,402,0,3,"Adams, Mr. John",male,26.0,0,0,341826,8.0500,S
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,S
207,208,1,3,"Albimona, Mr. Nassef Cassem",male,26.0,0,0,2699,18.7875,C

In [36]:
merged_df=pd.merge(df.head(2),df.tail(2),how='outer',indicator=True)

In [37]:
merged_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,_merge
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,left_only
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,left_only
2,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,right_only
3,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,right_only

In [38]:
group_df=df.groupby('Name')

In [41]:
for key,item in group_df:
  print(group_df.get_group(key),"\n\n")

Streaming output truncated to the last 5000 lines.
     Parch      Ticket  Fare Embarked
671      0  F.C. 12750  52.0        S


     PassengerId  Survived  Pclass                            Name   Sex  Age  \
549          550         1       2  Davies, Master. John Morgan Jr  male  8.0

     SibSp  Parch      Ticket   Fare Embarked
549      1      1  C.A. 33112  36.75        S


     PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
565          566         0       3  Davies, Mr. Alfred J  male  24.0      2

     Parch     Ticket   Fare Embarked
565      0  A/4 48871  24.15        S


     PassengerId  Survived  Pclass                       Name   Sex   Age  \
385          386         0       2  Davies, Mr. Charles Henry  male  18.0

     SibSp  Parch        Ticket  Fare Embarked
385      0      0  S.O.C. 14879  73.5        S


     PassengerId  Survived  Pclass               Name     Sex   Age  SibSp  \
635          636         1       2  Davis, Miss. Mary  female  28.0      0

     Parch  Ticket  Fare Embarked
635      0  237668  13.0        S


     PassengerId  Survived  Pclass                                       Name  \
347          348         1       3  Davison, Mrs. Thomas Henry (Mary E Finck)

        Sex        Age  SibSp  Parch  Ticket  Fare Embarked
347  female  29.699118      1      0  386525  16.1        S


     PassengerId  Survived  Pclass                        Name   Sex  Age  \
788          789         1       3  Dean, Master. Bertram Vere  male  1.0

     SibSp  Parch     Ticket    Fare Embarked
788      1      2  C.A. 2315  20.575        S


    PassengerId  Survived  Pclass                     Name   Sex   Age  SibSp  \
93           94         0       3  Dean, Mr. Bertram Frank  male  26.0      1

    Parch     Ticket    Fare Embarked
93      2  C.A. 2315  20.575        S


     PassengerId  Survived  Pclass                Name   Sex        Age  \
335          336         0       3  Denkoff, Mr. Mitto  male  29.699118

     SibSp  Parch  Ticket    Fare Embarked
335      0      0  349225  7.8958        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
320          321         0       3  Dennis, Mr. Samuel  male  22.0      0

     Parch     Ticket  Fare Embarked
320      0  A/5 21172  7.25        S


    PassengerId  Survived  Pclass                           Name     Sex  \
44           45         1       3  Devaney, Miss. Margaret Delia  female

     Age  SibSp  Parch  Ticket    Fare Embarked
44  19.0      0      0  330958  7.8792        Q


     PassengerId  Survived  Pclass                     Name   Sex   Age  \
690          691         1       1  Dick, Mr. Albert Adrian  male  31.0

     SibSp  Parch Ticket  Fare Embarked
690      1      0  17474  57.0        S


     PassengerId  Survived  Pclass                                       Name  \
781          782         1       1  Dick, Mrs. Albert Adrian (Vera Gillespie)

        Sex   Age  SibSp  Parch Ticket  Fare Embarked
781  female  17.0      1      0  17474  57.0        S


     PassengerId  Survived  Pclass              Name   Sex   Age  SibSp  \
349          350         0       3  Dimic, Mr. Jovan  male  42.0      0

     Parch  Ticket    Fare Embarked
349      0  315088  8.6625        S


     PassengerId  Survived  Pclass                       Name   Sex  Age  \
445          446         1       1  Dodge, Master. Washington  male  4.0

     SibSp  Parch Ticket     Fare Embarked
445      0      2  33638  81.8583        S


     PassengerId  Survived  Pclass                 Name   Sex        Age  \
568          569         0       3  Doharr, Mr. Tannous  male  29.699118

     SibSp  Parch Ticket    Fare Embarked
568      0      0   2686  7.2292        C


     PassengerId  Survived  Pclass                 Name     Sex   Age  SibSp  \
651          652         1       2  Doling, Miss. Elsie  female  18.0      0

     Parch  Ticket  Fare Embarked
651      1  231919  23.0        S


    PassengerId  Survived  Pclass                                  Name  \
98           99         1       2  Doling, Mrs. John T (Ada Julia Bone)

       Sex   Age  SibSp  Parch  Ticket  Fare Embarked
98  female  34.0      0      1  231919  23.0        S


     PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
890          891         0       3  Dooley, Mr. Patrick  male  32.0      0

     Parch  Ticket  Fare Embarked
890      0  370376  7.75        Q


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
283          284         1       3  Dorking, Mr. Edward Arthur  male  19.0

     SibSp  Parch      Ticket  Fare Embarked
283      0      0  A/5. 10482  8.05        S


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
544          545         0       1  Douglas, Mr. Walter Donald  male  50.0

     SibSp  Parch    Ticket     Fare Embarked
544      1      0  PC 17761  106.425        C


    PassengerId  Survived  Pclass                      Name     Sex   Age  \
79           80         1       3  Dowdell, Miss. Elizabeth  female  30.0

    SibSp  Parch  Ticket    Fare Embarked
79      0      0  364516  12.475        S


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
582          583         0       2  Downton, Mr. William James  male  54.0

     SibSp  Parch Ticket  Fare Embarked
582      0      0  28403  26.0        S


     PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
130          131         0       3  Drazenoic, Mr. Jozef  male  33.0      0

     Parch  Ticket    Fare Embarked
130      0  349241  7.8958        C


     PassengerId  Survived  Pclass  \
416          417         1       2

                                                Name     Sex   Age  SibSp  \
416  Drew, Mrs. James Vivian (Lulu Thorne Christian)  female  34.0      1

     Parch Ticket  Fare Embarked
416      1  28220  32.5        S


     PassengerId  Survived  Pclass              Name   Sex   Age  SibSp  \
280          281         0       3  Duane, Mr. Frank  male  65.0      0

     Parch  Ticket  Fare Embarked
280      0  336439  7.75        Q


     PassengerId  Survived  Pclass  \
556          557         1       1

                                                  Name     Sex   Age  SibSp  \
556  Duff Gordon, Lady. (Lucille Christiana Sutherl...  female  48.0      1

     Parch Ticket  Fare Embarked
556      0  11755  39.6        C


     PassengerId  Survived  Pclass  \
599          600         1       1

                                             Name   Sex   Age  SibSp  Parch  \
599  Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")  male  49.0      1      0

       Ticket     Fare Embarked
599  PC 17485  56.9292        C


     PassengerId  Survived  Pclass                          Name     Sex  \
866          867         1       2  Duran y More, Miss. Asuncion  female

      Age  SibSp  Parch         Ticket     Fare Embarked
866  27.0      1      0  SC/PARIS 2149  13.8583        C


     PassengerId  Survived  Pclass                            Name   Sex  \
675          676         0       3  Edvardsson, Mr. Gustaf Hjalmar  male

      Age  SibSp  Parch  Ticket   Fare Embarked
675  18.0      0      0  349912  7.775        S


     PassengerId  Survived  Pclass                          Name   Sex   Age  \
658          659         0       2  Eitemiller, Mr. George Floyd  male  23.0

     SibSp  Parch Ticket  Fare Embarked
658      0      0  29751  13.0        S


     PassengerId  Survived  Pclass                    Name   Sex   Age  SibSp  \
764          765         0       3  Eklund, Mr. Hans Linus  male  16.0      0

     Parch  Ticket   Fare Embarked
764      0  347074  7.775        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
129          130         0       3  Ekstrom, Mr. Johan  male  45.0      0

     Parch  Ticket   Fare Embarked
129      0  347061  6.975        S


     PassengerId  Survived  Pclass             Name   Sex        Age  SibSp  \
773          774         0       3  Elias, Mr. Dibo  male  29.699118      0

     Parch Ticket   Fare Embarked
773      0   2674  7.225        C


     PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
532          533         0       3  Elias, Mr. Joseph Jr  male  17.0      1

     Parch Ticket    Fare Embarked
532      1   2690  7.2292        C


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
352          353         0       3  Elias, Mr. Tannous  male  15.0      1

     Parch Ticket    Fare Embarked
352      1   2695  7.2292        C


     PassengerId  Survived  Pclass                        Name   Sex   Age  \
592          593         0       3  Elsbury, Mr. William James  male  47.0

     SibSp  Parch    Ticket  Fare Embarked
592      0      0  A/5 3902  7.25        S


     PassengerId  Survived  Pclass                           Name     Sex  \
777          778         1       3  Emanuel, Miss. Virginia Ethel  female

     Age  SibSp  Parch  Ticket    Fare Embarked
777  5.0      0      0  364516  12.475        S


    PassengerId  Survived  Pclass                     Name   Sex        Age  \
26           27         0       3  Emir, Mr. Farred Chehab  male  29.699118

    SibSp  Parch Ticket   Fare Embarked
26      0      0   2631  7.225        C


     PassengerId  Survived  Pclass                           Name     Sex  \
716          717         1       1  Endres, Miss. Caroline Louise  female

      Age  SibSp  Parch    Ticket     Fare Embarked
716  38.0      0      0  PC 17757  227.525        C


     PassengerId  Survived  Pclass                            Name     Sex  \
496          497         1       1  Eustis, Miss. Elizabeth Mussey  female

      Age  SibSp  Parch Ticket     Fare Embarked
496  54.0      1      0  36947  78.2667        C


     PassengerId  Survived  Pclass                       Name   Sex   Age  \
228          229         0       2  Fahlstrom, Mr. Arne Jonas  male  18.0

     SibSp  Parch  Ticket  Fare Embarked
228      0      0  236171  13.0        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
525          526         0       3  Farrell, Mr. James  male  40.5      0

     Parch  Ticket  Fare Embarked
525      0  367232  7.75        Q


     PassengerId  Survived  Pclass                Name   Sex        Age  \
527          528         0       1  Farthing, Mr. John  male  29.699118

     SibSp  Parch    Ticket      Fare Embarked
527      0      0  PC 17483  221.7792        S


    PassengerId  Survived  Pclass  \
53           54         1       2

                                                 Name     Sex   Age  SibSp  \
53  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.0      1

    Parch Ticket  Fare Embarked
53      0   2926  26.0        S


     PassengerId  Survived  Pclass                             Name   Sex  \
688          689         0       3  Fischer, Mr. Eberhard Thelander  male

      Age  SibSp  Parch  Ticket    Fare Embarked
688  18.0      0      0  350036  7.7958        S


     PassengerId  Survived  Pclass                     Name     Sex  \
306          307         1       1  Fleming, Miss. Margaret  female

           Age  SibSp  Parch Ticket      Fare Embarked
306  29.699118      0      0  17421  110.8833        C


     PassengerId  Survived  Pclass              Name   Sex        Age  SibSp  \
428          429         0       3  Flynn, Mr. James  male  29.699118      0

     Parch  Ticket  Fare Embarked
428      0  364851  7.75        Q


     PassengerId  Survived  Pclass             Name   Sex        Age  SibSp  \
825          826         0       3  Flynn, Mr. John  male  29.699118      0

     Parch  Ticket  Fare Embarked
825      0  368323  6.95        Q


     PassengerId  Survived  Pclass                              Name   Sex  \
572          573         1       1  Flynn, Mr. John Irwin ("Irving")  male

      Age  SibSp  Parch    Ticket     Fare Embarked
572  36.0      0      0  PC 17474  26.3875        S


     PassengerId  Survived  Pclass             Name   Sex        Age  SibSp  \
643          644         1       3  Foo, Mr. Choong  male  29.699118      0

     Parch Ticket     Fare Embarked
643      0   1601  56.4958        S


     PassengerId  Survived  Pclass                                  Name  \
436          437         0       3  Ford, Miss. Doolina Margaret "Daisy"

        Sex   Age  SibSp  Parch      Ticket    Fare Embarked
436  female  21.0      2      2  W./C. 6608  34.375        S


     PassengerId  Survived  Pclass                              Name     Sex  \
147          148         0       3  Ford, Miss. Robina Maggie "Ruby"  female

     Age  SibSp  Parch      Ticket    Fare Embarked
147  9.0      2      2  W./C. 6608  34.375        S


    PassengerId  Survived  Pclass                    Name   Sex   Age  SibSp  \
86           87         0       3  Ford, Mr. William Neal  male  16.0      1

    Parch      Ticket    Fare Embarked
86      3  W./C. 6608  34.375        S


     PassengerId  Survived  Pclass                                     Name  \
736          737         0       3  Ford, Mrs. Edward (Margaret Ann Watson)

        Sex   Age  SibSp  Parch      Ticket    Fare Embarked
736  female  48.0      1      3  W./C. 6608  34.375        S


     PassengerId  Survived  Pclass                             Name   Sex  \
452          453         0       1  Foreman, Mr. Benjamin Laventall  male

      Age  SibSp  Parch  Ticket   Fare Embarked
452  30.0      0      0  113051  27.75        C


     PassengerId  Survived  Pclass                            Name     Sex  \
341          342         1       1  Fortune, Miss. Alice Elizabeth  female

      Age  SibSp  Parch Ticket   Fare Embarked
341  24.0      3      2  19950  263.0        S


    PassengerId  Survived  Pclass                        Name     Sex   Age  \
88           89         1       1  Fortune, Miss. Mabel Helen  female  23.0

    SibSp  Parch Ticket   Fare Embarked
88      3      2  19950  263.0        S


    PassengerId  Survived  Pclass                            Name   Sex   Age  \
27           28         0       1  Fortune, Mr. Charles Alexander  male  19.0

    SibSp  Parch Ticket   Fare Embarked
27      3      2  19950  263.0        S


     PassengerId  Survived  Pclass               Name   Sex   Age  SibSp  \
438          439         0       1  Fortune, Mr. Mark  male  64.0      1

     Parch Ticket   Fare Embarked
438      4  19950  263.0        S


     PassengerId  Survived  Pclass                     Name   Sex   Age  \
344          345         0       2  Fox, Mr. Stanley Hubert  male  36.0

     SibSp  Parch  Ticket  Fare Embarked
344      0      0  229236  13.0        S


     PassengerId  Survived  Pclass                            Name     Sex  \
309          310         1       1  Francatelli, Miss. Laura Mabel  female

      Age  SibSp  Parch    Ticket     Fare Embarked
309  30.0      0      0  PC 17485  56.9292        C


     PassengerId  Survived  Pclass                           Name   Sex   Age  \
660          661         1       1  Frauenthal, Dr. Henry William  male  50.0

     SibSp  Parch    Ticket    Fare Embarked
660      2      0  PC 17611  133.65        S


     PassengerId  Survived  Pclass  \
334          335         1       1

                                                  Name     Sex        Age  \
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  female  29.699118

     SibSp  Parch    Ticket    Fare Embarked
334      1      0  PC 17611  133.65        S


     PassengerId  Survived  Pclass                                Name  \
539          540         1       1  Frolicher, Miss. Hedwig Margaritha

        Sex   Age  SibSp  Parch Ticket  Fare Embarked
539  female  22.0      0      2  13568  49.5        C


     PassengerId  Survived  Pclass                              Name   Sex  \
587          588         1       1  Frolicher-Stehli, Mr. Maxmillian  male

      Age  SibSp  Parch Ticket  Fare Embarked
587  60.0      1      1  13567  79.2        C


     PassengerId  Survived  Pclass                              Name   Sex  \
481          482         0       2  Frost, Mr. Anthony Wood "Archie"  male

           Age  SibSp  Parch  Ticket  Fare Embarked
481  29.699118      0      0  239854   0.0        S


     PassengerId  Survived  Pclass              Name   Sex        Age  SibSp  \
815          816         0       1  Fry, Mr. Richard  male  29.699118      0

     Parch  Ticket  Fare Embarked
815      0  112058   0.0        S


     PassengerId  Survived  Pclass                       Name     Sex   Age  \
357          358         0       2  Funk, Miss. Annie Clemmer  female  38.0

     SibSp  Parch  Ticket  Fare Embarked
357      0      0  237671  13.0        S


     PassengerId  Survived  Pclass                         Name   Sex   Age  \
137          138         0       1  Futrelle, Mr. Jacques Heath  male  37.0

     SibSp  Parch  Ticket  Fare Embarked
137      1      0  113803  53.1        S


   PassengerId  Survived  Pclass  \
3            4         1       1

                                           Name     Sex   Age  SibSp  Parch  \
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0

   Ticket  Fare Embarked
3  113803  53.1        S


    PassengerId  Survived  Pclass                  Name   Sex   Age  SibSp  \
20           21         0       2  Fynney, Mr. Joseph J  male  35.0      0

    Parch  Ticket  Fare Embarked
20      0  239865  26.0        S


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
405          406         0       2  Gale, Mr. Shadrach  male  34.0      1

     Parch Ticket  Fare Embarked
405      0  28664  21.0        S


     PassengerId  Survived  Pclass                   Name   Sex   Age  SibSp  \
703          704         0       3  Gallagher, Mr. Martin  male  25.0      0

     Parch Ticket    Fare Embarked
703      0  36864  7.7417        Q


     PassengerId  Survived  Pclass                Name   Sex        Age  \
760          761         0       3  Garfirth, Mr. John  male  29.699118

     SibSp  Parch  Ticket  Fare Embarked
760      0      0  358585  14.5        S


     PassengerId  Survived  Pclass                  Name     Sex   Age  SibSp  \
576          577         1       2  Garside, Miss. Ethel  female  34.0      0

     Parch  Ticket  Fare Embarked
576      0  243880  13.0        S


     PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
791          792         0       2  Gaskell, Mr. Alfred  male  16.0      0

     Parch  Ticket  Fare Embarked
791      0  239865  26.0        S


     PassengerId  Survived  Pclass                 Name   Sex   Age  SibSp  \
619          620         0       2  Gavey, Mr. Lawrence  male  26.0      0

     Parch Ticket  Fare Embarked
619      0  31028  10.5        S


     PassengerId  Survived  Pclass               Name   Sex   Age  SibSp  \
462          463         0       1  Gee, Mr. Arthur H  male  47.0      0

     Parch  Ticket  Fare Embarked
462      0  111320  38.5        S


     PassengerId  Survived  Pclass                    Name   Sex        Age  \
420          421         0       3  Gheorgheff, Mr. Stanio  male  29.699118

     SibSp  Parch  Ticket    Fare Embarked
420      0      0  349254  7.8958        C


     PassengerId  Survived  Pclass                Name   Sex   Age  SibSp  \
139          140         0       1  Giglio, Mr. Victor  male  24.0      0

     Parch    Ticket  Fare Embarked
139      0  PC 17593  79.2        C


     PassengerId  Survived  Pclass                         Name   Sex   Age  \
861          862         0       2  Giles, Mr. Frederick Edward  male  21.0

     SibSp  Parch Ticket  Fare Embarked
861      1      0  28134  11.5        S



In [42]:
group_df=df.groupby('Age')
for key,item in group_df:
  print(group_df.get_group(key),"\n\n")

     PassengerId  Survived  Pclass                             Name   Sex  \
803          804         1       3  Thomas, Master. Assad Alexander  male

      Age  SibSp  Parch Ticket    Fare Embarked
803  0.42      0      1   2625  8.5167        C


     PassengerId  Survived  Pclass                       Name   Sex   Age  \
755          756         1       2  Hamalainen, Master. Viljo  male  0.67

     SibSp  Parch  Ticket  Fare Embarked
755      1      1  250649  14.5        S


     PassengerId  Survived  Pclass                           Name     Sex  \
469          470         1       3  Baclini, Miss. Helene Barbara  female
644          645         1       3         Baclini, Miss. Eugenie  female

      Age  SibSp  Parch Ticket     Fare Embarked
469  0.75      2      1   2666  19.2583        C
644  0.75      2      1   2666  19.2583        C


     PassengerId  Survived  Pclass                             Name   Sex  \
78            79         1       2    Caldwell, Master. Alden Gates  male
831          832         1       2  Richards, Master. George Sibley  male

      Age  SibSp  Parch  Ticket   Fare Embarked
78   0.83      0      2  248738  29.00        S
831  0.83      1      1   29106  18.75        S


     PassengerId  Survived  Pclass                            Name   Sex  \
305          306         1       1  Allison, Master. Hudson Trevor  male

      Age  SibSp  Parch  Ticket    Fare Embarked
305  0.92      1      2  113781  151.55        S


     PassengerId  Survived  Pclass                             Name     Sex  \
164          165         0       3     Panula, Master. Eino Viljami    male
172          173         1       3     Johnson, Miss. Eleanor Ileen  female
183          184         1       2        Becker, Master. Richard F    male
381          382         1       3      Nakid, Miss. Maria ("Mary")  female
386          387         0       3  Goodwin, Master. Sidney Leonard    male
788          789         1       3       Dean, Master. Bertram Vere    male
827          828         1       2            Mallet, Master. Andre    male

     Age  SibSp  Parch           Ticket     Fare Embarked
164  1.0      4      1          3101295  39.6875        S
172  1.0      1      1           347742  11.1333        S
183  1.0      2      1           230136  39.0000        S
381  1.0      0      2             2653  15.7417        C
386  1.0      5      2          CA 2144  46.9000        S
788  1.0      1      2        C.A. 2315  20.5750        S
827  1.0      0      2  S.C./PARIS 2079  37.0042        C


     PassengerId  Survived  Pclass                               Name     Sex  \
7              8         0       3     Palsson, Master. Gosta Leonard    male
16            17         0       3               Rice, Master. Eugene    male
119          120         0       3  Andersson, Miss. Ellis Anna Maria  female
205          206         0       3         Strom, Miss. Telma Matilda  female
297          298         0       1       Allison, Miss. Helen Loraine  female
340          341         1       2     Navratil, Master. Edmond Roger    male
479          480         1       3           Hirvonen, Miss. Hildur E  female
530          531         1       2           Quick, Miss. Phyllis May  female
642          643         0       3      Skoog, Miss. Margit Elizabeth  female
824          825         0       3       Panula, Master. Urho Abraham    male

     Age  SibSp  Parch   Ticket      Fare Embarked
7    2.0      3      1   349909   21.0750        S
16   2.0      4      1   382652   29.1250        Q
119  2.0      4      2   347082   31.2750        S
205  2.0      0      1   347054   10.4625        S
297  2.0      1      2   113781  151.5500        S
340  2.0      1      1   230080   26.0000        S
479  2.0      0      1  3101298   12.2875        S
530  2.0      1      1    26360   26.0000        S
642  2.0      3      2   347088   27.9000        S
824  2.0      4      1  3101295   39.6875        S


     PassengerId  Survived  Pclass                                      Name  \
43            44         1       2  Laroche, Miss. Simonne Marie Anne Andree
193          194         1       2                Navratil, Master. Michel M
261          262         1       3         Asplund, Master. Edvin Rojj Felix
348          349         1       3    Coutts, Master. William Loch "William"
374          375         0       3                Palsson, Miss. Stina Viola
407          408         1       2            Richards, Master. William Rowe

        Sex  Age  SibSp  Parch         Ticket     Fare Embarked
43   female  3.0      1      2  SC/Paris 2123  41.5792        C
193    male  3.0      1      1         230080  26.0000        S
261    male  3.0      4      2         347077  31.3875        S
348    male  3.0      1      1     C.A. 37671  15.9000        S
374  female  3.0      3      1         349909  21.0750        S
407    male  3.0      1      1          29106  18.7500        S


     PassengerId  Survived  Pclass                                     Name  \
10            11         1       3          Sandstrom, Miss. Marguerite Rut
63            64         0       3                    Skoog, Master. Harald
171          172         0       3                     Rice, Master. Arthur
184          185         1       3      Kink-Heilmann, Miss. Luise Gretchen
445          446         1       1                Dodge, Master. Washington
618          619         1       2              Becker, Miss. Marion Louise
691          692         1       3                       Karun, Miss. Manca
750          751         1       2                        Wells, Miss. Joan
850          851         0       3  Andersson, Master. Sigvard Harald Elias
869          870         1       3          Johnson, Master. Harold Theodor

        Sex  Age  SibSp  Parch   Ticket     Fare Embarked
10   female  4.0      1      1  PP 9549  16.7000        S
63     male  4.0      3      2   347088  27.9000        S
171    male  4.0      4      1   382652  29.1250        Q
184  female  4.0      0      2   315153  22.0250        S
445    male  4.0      0      2    33638  81.8583        S
618  female  4.0      2      1   230136  39.0000        S
691  female  4.0      0      1   349256  13.4167        C
750  female  4.0      1      1    29103  23.0000        S
850    male  4.0      4      2   347082  31.2750        S
869    male  4.0      1      1   347742  11.1333        S


     PassengerId  Survived  Pclass                            Name     Sex  \
58            59         1       2    West, Miss. Constance Mirium  female
233          234         1       3  Asplund, Miss. Lillian Gertrud  female
448          449         1       3  Baclini, Miss. Marie Catherine  female
777          778         1       3   Emanuel, Miss. Virginia Ethel  female

     Age  SibSp  Parch      Ticket     Fare Embarked
58   5.0      1      2  C.A. 34651  27.7500        S
233  5.0      4      2      347077  31.3875        S
448  5.0      2      1        2666  19.2583        C
777  5.0      0      0      364516  12.4750        S


     PassengerId  Survived  Pclass                                Name  \
720          721         1       2   Harper, Miss. Annie Jessie "Nina"
751          752         1       3                 Moor, Master. Meier
813          814         0       3  Andersson, Miss. Ebba Iris Alfrida

        Sex  Age  SibSp  Parch  Ticket    Fare Embarked
720  female  6.0      0      1  248727  33.000        S
751    male  6.0      0      1  392096  12.475        S
813  female  6.0      4      2  347082  31.275        S


     PassengerId  Survived  Pclass                        Name     Sex  Age  \
50            51         0       3  Panula, Master. Juha Niilo    male  7.0
278          279         0       3          Rice, Master. Eric    male  7.0
535          536         1       2      Hart, Miss. Eva Miriam  female  7.0

     SibSp  Parch        Ticket     Fare Embarked
50       4      1       3101295  39.6875        S
278      4      1        382652  29.1250        Q
535      0      2  F.C.C. 13529  26.2500        S


     PassengerId  Survived  Pclass                              Name     Sex  \
24            25         0       3     Palsson, Miss. Torborg Danira  female
237          238         1       2  Collyer, Miss. Marjorie "Lottie"  female
549          550         1       2    Davies, Master. John Morgan Jr    male
787          788         0       3         Rice, Master. George Hugh    male

     Age  SibSp  Parch      Ticket    Fare Embarked
24   8.0      3      1      349909  21.075        S
237  8.0      0      2  C.A. 31921  26.250        S
549  8.0      1      1  C.A. 33112  36.750        S
787  8.0      4      1      382652  29.125        Q


     PassengerId  Survived  Pclass  \
147          148         0       3
165          166         1       3
182          183         0       3
480          481         0       3
489          490         1       3
541          542         0       3
634          635         0       3
852          853         0       3

                                                Name     Sex  Age  SibSp  \
147                 Ford, Miss. Robina Maggie "Ruby"  female  9.0      2
165  Goldsmith, Master. Frank John William "Frankie"    male  9.0      0
182            Asplund, Master. Clarence Gustaf Hugo    male  9.0      4
480                   Goodwin, Master. Harold Victor    male  9.0      5
489            Coutts, Master. Eden Leslie "Neville"    male  9.0      1
541             Andersson, Miss. Ingeborg Constanzia  female  9.0      4
634                               Skoog, Miss. Mabel  female  9.0      3
852                          Boulos, Miss. Nourelain  female  9.0      1

     Parch      Ticket     Fare Embarked
147      2  W./C. 6608  34.3750        S
165      2      363291  20.5250        S
182      2      347077  31.3875        S
480      2     CA 2144  46.9000        S
489      1  C.A. 37671  15.9000        S
541      2      347082  31.2750        S
634      2      347088  27.9000        S
852      1        2678  15.2458        C


     PassengerId  Survived  Pclass                          Name     Sex  \
419          420         0       3     Van Impe, Miss. Catharina  female
819          820         0       3  Skoog, Master. Karl Thorsten    male

      Age  SibSp  Parch  Ticket   Fare Embarked
419  10.0      0      2  345773  24.15        S
819  10.0      3      2  347088  27.90        S


     PassengerId  Survived  Pclass                                 Name  \
59            60         0       3   Goodwin, Master. William Frederick
542          543         0       3    Andersson, Miss. Sigrid Elisabeth
731          732         0       3             Hassan, Mr. Houssein G N
802          803         1       1  Carter, Master. William Thornton II

        Sex   Age  SibSp  Parch   Ticket      Fare Embarked
59     male  11.0      5      2  CA 2144   46.9000        S
542  female  11.0      4      2   347082   31.2750        S
731    male  11.0      0      0     2699   18.7875        C
802    male  11.0      1      2   113760  120.0000        S


     PassengerId  Survived  Pclass                          Name   Sex   Age  \
125          126         1       3  Nicola-Yarred, Master. Elias  male  12.0

     SibSp  Parch Ticket     Fare Embarked
125      1      0   2651  11.2417        C


     PassengerId  Survived  Pclass                               Name     Sex  \
446          447         1       2  Mellinger, Miss. Madeleine Violet  female
780          781         1       3               Ayoub, Miss. Banoura  female

      Age  SibSp  Parch  Ticket     Fare Embarked
446  13.0      0      1  250644  19.5000        S
780  13.0      0      0    2687   7.2292        C


     PassengerId  Survived  Pclass                                  Name  \
9             10         1       2   Nasser, Mrs. Nicholas (Adele Achem)
14            15         0       3  Vestrom, Miss. Hulda Amanda Adolfina
39            40         1       3           Nicola-Yarred, Miss. Jamila
435          436         1       1             Carter, Miss. Lucile Polk
683          684         0       3           Goodwin, Mr. Charles Edward
686          687         0       3              Panula, Mr. Jaako Arnold

        Sex   Age  SibSp  Parch   Ticket      Fare Embarked
9    female  14.0      1      0   237736   30.0708        C
14   female  14.0      0      0   350406    7.8542        S
39   female  14.0      1      0     2651   11.2417        C
435  female  14.0      1      2   113760  120.0000        S
683    male  14.0      5      2  CA 2144   46.9000        S
686    male  14.0      4      1  3101295   39.6875        S


     PassengerId  Survived  Pclass                  Name     Sex   Age  SibSp  \
111          112         0       3  Zabour, Miss. Hileni  female  14.5      1

     Parch Ticket     Fare Embarked
111      0   2665  14.4542        C


     PassengerId  Survived  Pclass                                     Name  \
22            23         1       3              McGowan, Miss. Anna "Annie"
352          353         0       3                       Elias, Mr. Tannous
689          690         1       1        Madill, Miss. Georgette Alexandra
830          831         1       3  Yasbeck, Mrs. Antoni (Selini Alexander)
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"

        Sex   Age  SibSp  Parch  Ticket      Fare Embarked
22   female  15.0      0      0  330923    8.0292        Q
352    male  15.0      1      1    2695    7.2292        C
689  female  15.0      0      1   24160  211.3375        S
830  female  15.0      1      0    2659   14.4542        C
875  female  15.0      0      0    2667    7.2250        C


     PassengerId  Survived  Pclass                              Name     Sex  \
71            72         0       3        Goodwin, Miss. Lillian Amy  female
86            87         0       3            Ford, Mr. William Neal    male
138          139         0       3               Osen, Mr. Olaf Elon    male
156          157         1       3  Gilnagh, Miss. Katherine "Katie"  female
208          209         1       3         Carr, Miss. Helen "Ellen"  female
220          221         1       3    Sunderland, Mr. Victor Francis    male
266          267         0       3         Panula, Mr. Ernesti Arvid    male
282          283         0       3         de Pelsmaeker, Mr. Alfons    male
329          330         1       1      Hippach, Miss. Jean Gertrude  female
333          334         0       3   Vander Planke, Mr. Leo Edmondus    male
504          505         1       1             Maioni, Miss. Roberta  female
574          575         0       3      Rush, Mr. Alfred George John    male
746          747         0       3       Abbott, Mr. Rossmore Edward    male
764          765         0       3            Eklund, Mr. Hans Linus    male
791          792         0       2               Gaskell, Mr. Alfred    male
841          842         0       2          Mudd, Mr. Thomas Charles    male
853          854         1       1         Lines, Miss. Mary Conover  female

      Age  SibSp  Parch           Ticket     Fare Embarked
71   16.0      5      2          CA 2144  46.9000        S
86   16.0      1      3       W./C. 6608  34.3750        S
138  16.0      0      0             7534   9.2167        S
156  16.0      0      0            35851   7.7333        Q
208  16.0      0      0           367231   7.7500        Q
220  16.0      0      0  SOTON/OQ 392089   8.0500        S
266  16.0      4      1          3101295  39.6875        S
282  16.0      0      0           345778   9.5000        S
329  16.0      0      1           111361  57.9792        C
333  16.0      2      0           345764  18.0000        S
504  16.0      0      0           110152  86.5000        S
574  16.0      0      0       A/4. 20589   8.0500        S
746  16.0      1      1        C.A. 2673  20.2500        S
764  16.0      0      0           347074   7.7750        S
791  16.0      0      0           239865  26.0000        S
841  16.0      0      0      S.O./P.P. 3  10.5000        S
853  16.0      0      1         PC 17592  39.4000        S


     PassengerId  Survived  Pclass  \
68            69         1       3
84            85         1       2
114          115         0       3
163          164         0       3
307          308         1       1
389          390         1       2
433          434         0       3
500          501         0       3
532          533         0       3
550          551         1       1
721          722         0       3
781          782         1       1
844          845         0       3

                                                  Name     Sex   Age  SibSp  \
68                     Andersson, Miss. Erna Alexandra  female  17.0      4
84                                 Ilett, Miss. Bertha  female  17.0      0
114                              Attalah, Miss. Malake  female  17.0      0
163                                    Calic, Mr. Jovo    male  17.0      0
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1
389                              Lehmann, Miss. Bertha  female  17.0      0
433                         Kallio, Mr. Nikolai Erland    male  17.0      0
500                                   Calic, Mr. Petar    male  17.0      0
532                               Elias, Mr. Joseph Jr    male  17.0      1
550                        Thayer, Mr. John Borland Jr    male  17.0      0
721                          Jensen, Mr. Svend Lauritz    male  17.0      1
781          Dick, Mrs. Albert Adrian (Vera Gillespie)  female  17.0      1
844                                Culumovic, Mr. Jeso    male  17.0      0

     Parch             Ticket      Fare Embarked
68       2            3101281    7.9250        S
84       0         SO/C 14885   10.5000        S
114      0               2627   14.4583        C
163      0             315093    8.6625        S
307      0           PC 17758  108.9000        C
389      0            SC 1748   12.0000        C
433      0  STON/O 2. 3101274    7.1250        S
500      0             315086    8.6625        S
532      1               2690    7.2292        C
550      2              17421  110.8833        C
721      0             350048    7.0542        S
781      0              17474   57.0000        S
844      0             315090    8.6625        S


     PassengerId  Survived  Pclass  \
38            39         0       3
49            50         0       3
144          145         0       2
175          176         0       3
204          205         1       3
228          229         0       2
311          312         1       1
371          372         0       3
385          386         0       2
417          418         1       2
424          425         0       3
505          506         0       1
585          586         1       1
651          652         1       2
654          655         0       3
675          676         0       3
677          678         1       3
688          689         0       3
700          701         1       1
702          703         0       3
757          758         0       2
775          776         0       3
786          787         1       3
807          808         0       3
834          835         0       3
855          856         1       3

                                                  Name     Sex   Age  SibSp  \
38                  Vander Planke, Miss. Augusta Maria  female  18.0      2
49       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.0      1
144                         Andrew, Mr. Edgardo Samuel    male  18.0      0
175                             Klasen, Mr. Klas Albin    male  18.0      1
204                           Cohen, Mr. Gurshon "Gus"    male  18.0      0
228                          Fahlstrom, Mr. Arne Jonas    male  18.0      0